"use client";
import {ensureSession} from "@/lib/client-session";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Checkbox} from "@/components/ui/checkbox";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {emptySchedule,WeeklySchedule,shiftsForMonth,validSchedule,validMonth} from "@/lib/weekly";
import type {Shift} from "@/lib/pay";
const names=["日","月","火","水","木","金","土"];
export default function WeeklyEditor({month,shifts,onApplied}:{month:string,shifts:Shift[],onApplied:()=>Promise<void>}){
 const [schedule,setSchedule]=useState<WeeklySchedule>(emptySchedule),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[confirm,setConfirm]=useState(false);
 async function load(){try{await ensureSession();const r=await fetch("/api/weekly");const d=await r.json();if(!r.ok)throw Error(d.error);setSchedule(d.schedule);setReady(true);setError("");}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load()},[]);
 function update(index:number,key:string,value:unknown){setSchedule(s=>s.map((day,i)=>i===index?{...day,[key]:value}:day));setNotice("");}
 const valid=validSchedule(schedule)&&validMonth(month);const planned=valid?shiftsForMonth(month,schedule):[];const occupied=new Set(shifts.map(s=>s.date));const count=planned.filter(s=>!occupied.has(s.date)).length;const skipped=planned.length-count;
 async function persist(apply:boolean){setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/weekly",{method:apply?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({schedule,month})});const d=await r.json();if(!r.ok)throw Error(d.error);if(apply){await onApplied();setNotice(`${month.replace("-","年")}月に${d.created}件登録しました${d.skipped?`（登録済みの${d.skipped}日はスキップ）`:""}`);}else setNotice("曜日ごとの固定シフトを保存しました");setConfirm(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="weekly-panel"><div className="weekly-heading"><div><h2>曜日ごとの固定シフト</h2><p>いつもの勤務時間を保存して、選んだ月にまとめて登録。</p></div><span className="weekly-count">{schedule.filter(s=>s.enabled).length}曜日を設定</span></div><div className="weekday-grid">{[1,2,3,4,5,6,0].map(i=><div key={i} className={`weekday ${schedule[i].enabled?"enabled":""}`}><label className={`weekday-label ${i===0||i===6?"weekend":""}`}><Checkbox checked={schedule[i].enabled} onCheckedChange={v=>update(i,"enabled",v===true)} disabled={!ready||busy}/>{names[i]}曜日</label><label className="week-time-label">開始<input type="time" value={schedule[i].start} disabled={!ready||busy||!schedule[i].enabled} onChange={e=>update(i,"start",e.target.value)}/></label><label className="week-time-label">終了<input type="time" value={schedule[i].end} disabled={!ready||busy||!schedule[i].enabled} onChange={e=>update(i,"end",e.target.value)}/></label></div>)}</div><div className="weekly-bottom"><p>{month.replace("-","年 ")}月：<strong>{count}件</strong>を追加予定{skipped>0&&`・登録済みの${skipped}日はスキップ`}<small>祝日も曜日の設定どおり登録されます。登録後は各日のシフトを編集・削除できます。</small></p><div className="weekly-buttons"><Button variant="outline" disabled={!ready||busy||!valid} onClick={()=>persist(false)}>固定シフトを保存</Button><Button disabled={!ready||busy||!valid||planned.length===0} onClick={()=>setConfirm(true)}>保存して{Number(month.slice(5))}月に登録</Button></div></div>{notice&&<p role="status" className="success">{notice}</p>}{error&&<p role="alert" className="weekly-error">{error} {!ready&&<Button variant="ghost" onClick={load}>再読み込み</Button>}</p>}<AlertDialog open={confirm} onOpenChange={v=>{if(!busy)setConfirm(v)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{month.replace("-","年 ")}月に固定シフトを登録しますか？</AlertDialogTitle><AlertDialogDescription>{count}件を追加予定です。登録済みの日は上書きせずスキップします。曜日ごとの設定も保存します。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>キャンセル</AlertDialogCancel><Button disabled={busy} onClick={()=>persist(true)}>{busy?"登録中…":"まとめて登録する"}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
